#################
# Enable Bluetooth
#################
# CONFIG_SMP=y

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_HCI=y
CONFIG_BT_DEVICE_NAME="SensorNode"
CONFIG_BT_BUF_ACL_RX_SIZE=200
CONFIG_BT_BUF_ACL_TX_SIZE=200
CONFIG_BT_L2CAP_TX_MTU=71

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_SENSOR_INIT_PRIORITY=95

# Enable Peripheral
#enabled GPIO for button
CONFIG_GPIO=y
# CONFIG_WATCHDOG=n
# enable prints for serial
CONFIG_PRINTK=y
# enable floating point suppport
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_I2C=y

CONFIG_SENSOR=y
CONFIG_SENSOR_ASYNC_API=y

# Enable Zephyr logging
CONFIG_LOG=y
# Set the default log level
CONFIG_LOG_DEFAULT_LEVEL=3


# Enable Zephyr shell
CONFIG_SHELL=y
# Backend the logs to be output via the shell
CONFIG_SHELL_LOG_BACKEND=y
# Add runtime log commands
CONFIG_LOG_CMDS=y

#for JSON libraries
CONFIG_JSON_LIBRARY=y

# fs_dirent structures are big.
CONFIG_MAIN_STACK_SIZE=4096

# CONFIG_FLASH=y 
# CONFIG_FLASH_MAP=y

# CONFIG_FILE_SYSTEM=y
# CONFIG_FILE_SYSTEM_LITTLEFS=y


